<!DOCTYPE html>
<!-- saved from url=(0056)https://nodejs.org/dist/latest-v6.x/docs/api/errors.html -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  
  <title>Errors Node.js v6.3.1 Manual &amp; Documentation</title>
  <link rel="stylesheet" href="./Errors Node.js v6.3.1 Manual &amp; Documentation_files/css">
  <link rel="stylesheet" href="./Errors Node.js v6.3.1 Manual &amp; Documentation_files/style.css">
  <link rel="stylesheet" href="./Errors Node.js v6.3.1 Manual &amp; Documentation_files/sh.css">
  <link rel="canonical" href="https://nodejs.org/api/errors.html">
<style type="text/css">
:root #content > #right > .dose > .dosesingle,
:root #content > #center > .dose > .dosesingle
{ display: none !important; }</style><style></style></head>
<body class="alt apidoc" id="api-section-errors">
  <div id="content" class="clearfix">
    <div id="column2" class="interior">
      <div id="intro" class="interior">
        <a href="https://nodejs.org/" title="Go back to the home page">
          Node.js
        </a>
      </div>
      <ul>
<li><a class="nav-documentation" href="https://nodejs.org/dist/latest-v6.x/docs/api/documentation.html">About these Docs</a></li>
<li><a class="nav-synopsis" href="https://nodejs.org/dist/latest-v6.x/docs/api/synopsis.html">Usage &amp; Example</a></li>
</ul>
<div class="line"></div>

<ul>
<li><a class="nav-assert" href="https://nodejs.org/dist/latest-v6.x/docs/api/assert.html">Assertion Testing</a></li>
<li><a class="nav-buffer" href="https://nodejs.org/dist/latest-v6.x/docs/api/buffer.html">Buffer</a></li>
<li><a class="nav-addons" href="https://nodejs.org/dist/latest-v6.x/docs/api/addons.html">C/C++ Addons</a></li>
<li><a class="nav-child_process" href="https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html">Child Processes</a></li>
<li><a class="nav-cluster" href="https://nodejs.org/dist/latest-v6.x/docs/api/cluster.html">Cluster</a></li>
<li><a class="nav-cli" href="https://nodejs.org/dist/latest-v6.x/docs/api/cli.html">Command Line Options</a></li>
<li><a class="nav-console" href="https://nodejs.org/dist/latest-v6.x/docs/api/console.html">Console</a></li>
<li><a class="nav-crypto" href="https://nodejs.org/dist/latest-v6.x/docs/api/crypto.html">Crypto</a></li>
<li><a class="nav-debugger" href="https://nodejs.org/dist/latest-v6.x/docs/api/debugger.html">Debugger</a></li>
<li><a class="nav-dns" href="https://nodejs.org/dist/latest-v6.x/docs/api/dns.html">DNS</a></li>
<li><a class="nav-domain" href="https://nodejs.org/dist/latest-v6.x/docs/api/domain.html">Domain</a></li>
<li><a class="nav-errors active" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html">Errors</a></li>
<li><a class="nav-events" href="https://nodejs.org/dist/latest-v6.x/docs/api/events.html">Events</a></li>
<li><a class="nav-fs" href="https://nodejs.org/dist/latest-v6.x/docs/api/fs.html">File System</a></li>
<li><a class="nav-globals" href="https://nodejs.org/dist/latest-v6.x/docs/api/globals.html">Globals</a></li>
<li><a class="nav-http" href="https://nodejs.org/dist/latest-v6.x/docs/api/http.html">HTTP</a></li>
<li><a class="nav-https" href="https://nodejs.org/dist/latest-v6.x/docs/api/https.html">HTTPS</a></li>
<li><a class="nav-modules" href="https://nodejs.org/dist/latest-v6.x/docs/api/modules.html">Modules</a></li>
<li><a class="nav-net" href="https://nodejs.org/dist/latest-v6.x/docs/api/net.html">Net</a></li>
<li><a class="nav-os" href="https://nodejs.org/dist/latest-v6.x/docs/api/os.html">OS</a></li>
<li><a class="nav-path" href="https://nodejs.org/dist/latest-v6.x/docs/api/path.html">Path</a></li>
<li><a class="nav-process" href="https://nodejs.org/dist/latest-v6.x/docs/api/process.html">Process</a></li>
<li><a class="nav-punycode" href="https://nodejs.org/dist/latest-v6.x/docs/api/punycode.html">Punycode</a></li>
<li><a class="nav-querystring" href="https://nodejs.org/dist/latest-v6.x/docs/api/querystring.html">Query Strings</a></li>
<li><a class="nav-readline" href="https://nodejs.org/dist/latest-v6.x/docs/api/readline.html">Readline</a></li>
<li><a class="nav-repl" href="https://nodejs.org/dist/latest-v6.x/docs/api/repl.html">REPL</a></li>
<li><a class="nav-stream" href="https://nodejs.org/dist/latest-v6.x/docs/api/stream.html">Stream</a></li>
<li><a class="nav-string_decoder" href="https://nodejs.org/dist/latest-v6.x/docs/api/string_decoder.html">String Decoder</a></li>
<li><a class="nav-timers" href="https://nodejs.org/dist/latest-v6.x/docs/api/timers.html">Timers</a></li>
<li><a class="nav-tls" href="https://nodejs.org/dist/latest-v6.x/docs/api/tls.html">TLS/SSL</a></li>
<li><a class="nav-tty" href="https://nodejs.org/dist/latest-v6.x/docs/api/tty.html">TTY</a></li>
<li><a class="nav-dgram" href="https://nodejs.org/dist/latest-v6.x/docs/api/dgram.html">UDP/Datagram</a></li>
<li><a class="nav-url" href="https://nodejs.org/dist/latest-v6.x/docs/api/url.html">URL</a></li>
<li><a class="nav-util" href="https://nodejs.org/dist/latest-v6.x/docs/api/util.html">Utilities</a></li>
<li><a class="nav-v8" href="https://nodejs.org/dist/latest-v6.x/docs/api/v8.html">V8</a></li>
<li><a class="nav-vm" href="https://nodejs.org/dist/latest-v6.x/docs/api/vm.html">VM</a></li>
<li><a class="nav-zlib" href="https://nodejs.org/dist/latest-v6.x/docs/api/zlib.html">ZLIB</a></li>
</ul>
<div class="line"></div>

<ul>
<li><a class="nav-https-github-com-nodejs-node" href="https://github.com/nodejs/node">GitHub Repo &amp; Issue Tracker</a></li>
<li><a class="nav-http-groups-google-com-group-nodejs" href="http://groups.google.com/group/nodejs">Mailing List</a></li>
</ul>

    </div>

    <div id="column1" data-id="errors" class="interior">
      <header>
        <h1>Node.js v6.3.1 Documentation</h1>
        <div id="gtoc">
          <p>
            <a href="https://nodejs.org/dist/latest-v6.x/docs/api/index.html" name="toc">Index</a> |
            <a href="https://nodejs.org/dist/latest-v6.x/docs/api/all.html">View on single page</a> |
            <a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.json">View as JSON</a>
          </p>
        </div>
        <hr>
      </header>

      <div id="toc">
        <h2>Table of Contents</h2>
        <ul>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_errors">Ошибки</a><ul>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_propagation_and_interception">Распространение и перехват ошибок</a><ul>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_node_js_style_callbacks">callback-и в стиле Node.js </a></li>
</ul>
</li>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_class_error">Class: Error</a><ul>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_new_error_message">new Error(message)</a></li>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_capturestacktrace_targetobject_constructoropt">Error.captureStackTrace(targetObject[, constructorOpt])</a></li>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_stacktracelimit">Error.stackTraceLimit</a><ul>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_message">error.message</a></li>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_stack">error.stack</a></li>
</ul>
</li>
</ul>
</li>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_class_rangeerror">Class: RangeError</a></li>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_class_referenceerror">Class: ReferenceError</a></li>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_class_syntaxerror">Class: SyntaxError</a></li>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_class_typeerror">Class: TypeError</a></li>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_exceptions_vs_errors">Исключения и ошибки</a></li>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_system_errors">Системные ошибки</a><ul>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_class_system_error">Class: System Error</a><ul>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_code">error.code</a></li>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_errno">error.errno</a></li>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_syscall">error.syscall</a></li>
</ul>
</li>
<li><a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_common_system_errors">Общие системные ошибки</a></li>
</ul>
</li>
</ul>
</li>
</ul>

      </div>

      <div id="apicontent">
        <h1>Ошибки<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_errors" id="errors_errors">#</a></span></h1>
<!--type=misc-->
<p>В приложениях, работающих в Node.js, как правило, происходят ошибки четырех категорий:</p>
<ul>
<li>Стандартные ошибки JavaScript такие как:<ul>
<li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError" class="type">&lt;EvalError&gt;</a> : кидаются при неудачном вызове <code>eval()</code>.</li>
<li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError" class="type">&lt;SyntaxError&gt;</a>
 : кидаются в ответ на неправильный синтаксис JavaScript.</li>
<li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError" class="type">&lt;RangeError&gt;</a> : кидаются, когда значение находится за пределами ожидаемого диапозона</li>
<li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError" class="type">&lt;ReferenceError&gt;</a> : кидаются при использовании неопределенных переменных</li>
<li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError" class="type">&lt;TypeError&gt;</a> : 
кидаются при передаче аргументов неправильного типа</li>
<li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError" class="type">&lt;URIError&gt;</a> : 
кидаются при ошибках в глобальных функциях обработки URI.</li>
</ul>
</li>
<li>Системные ошибки вызываются базовыми ограничениями операционной системы, такими, как попытка открыть файл, которого не существует, 
попытка послать данные через закрытый сокет, и т.д.;</li>
<li>Ошибки, определенные пользователем, вызываются кодом программы.</li>
<li>Ошибки утвержений (Assertion Errors) - специальный класс ошибок, которые могут вызываться всегда, когда
Node.js обнаруживает исключительное нарушение логики, которое никогда не должно происходить. 
Они обычно вызываются модулем <code>assert</code>.</li>
</ul>
<p>Все ошибки JavaScript и системные ошибки, генерируемые Node.js, наследуются от или являются экземплярами
стандартного JavaScript класса <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error" class="type">&lt;Error&gt;</a> и гарантированно предоставляют
<em>по крайней мере</em> свойства, доступные в этом классе.</p>
<h2>Распространение и перехват ошибок<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_propagation_and_interception" id="errors_error_propagation_and_interception">#</a></span></h2>
<!--type=misc-->
<p>Node.js поддерживает несколько механизмов для распространения и обработки ошибок, которые
возникают во время работы приложения. Как эти ошибки доходят до пользователя и
обрабатываются, польностью зависит от типа ошибки и стиля API, который вызван (?).</p>
<p>Все ошибки JavaScript обрабатываются как исключения, которые <em>сразу</em> генерируют
и кидают ошибку, используя стандартный механизм JavaScript <code>throw</code>. 
Они обрабатываются с использованием <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch">конструкции <code>try / catch</code></a>, предоставляемой языком JavaScript.</p>
<pre class="sh_sourceCode"><code class="lang-js"><span class="sh_comment">// Кидается ReferenceError, т.к. z не определена</span>
<span class="sh_keyword">try</span> <span class="sh_cbracket">{</span>
  <span class="sh_keyword">const</span> m <span class="sh_symbol">=</span> <span class="sh_number">1</span><span class="sh_symbol">;</span>
  <span class="sh_keyword">const</span> n <span class="sh_symbol">=</span> m <span class="sh_symbol">+</span> z<span class="sh_symbol">;</span>
<span class="sh_cbracket">}</span> <span class="sh_keyword">catch</span> <span class="sh_symbol">(</span>err<span class="sh_symbol">)</span> <span class="sh_cbracket">{</span>
  <span class="sh_comment">// здесь обработка ошибки.</span>
<span class="sh_cbracket">}</span>
</code></pre>
<p>Любое использование механизма JavaScript <code>throw</code> создает исключение, которое
<em>обязано</em> обрабатываться с использованием конструкции <code>try / catch</code> или Node.js немедленно завершит работу.</p>
<p>За некоторыми исключениями, <em>синхронные</em> API (любые блокирующие методы, которые не принимают <code>callback</code> функцию, такие как <a href="https://nodejs.org/dist/latest-v6.x/docs/api/fs.html#fs_fs_readfilesync_file_options"><code>fs.readFileSync</code></a>), будут использовать <code>throw</code>
чтобы сообщить об ошибке.</p>
<p>Ошибки, которые возникают в <em>Асинхронном API</em>, могут обрабатываться разными способами:</p>
<ul>
<li><p>Большинство асинхронных методов, которые принимают <code>callback</code> функцию, будут принимать объект
<code>Error</code>, переданный как первый аргумент к этой функции. Если этот первый
аргумент не <code>null</code> и является экземпляром <code>Error</code>, то это значит, что произошла ошибка,
которая доложна быть обработана.</p>
<pre class="sh_sourceCode"><code class="lang-js"><span class="sh_keyword">const</span> fs <span class="sh_symbol">=</span> <span class="sh_function">require</span><span class="sh_symbol">(</span><span class="sh_string">'fs'</span><span class="sh_symbol">);</span>
fs<span class="sh_symbol">.</span><span class="sh_function">readFile</span><span class="sh_symbol">(</span><span class="sh_string">'файл, который не существует'</span><span class="sh_symbol">,</span> <span class="sh_symbol">(</span>err<span class="sh_symbol">,</span> data<span class="sh_symbol">)</span> <span class="sh_symbol">=&gt;</span> <span class="sh_cbracket">{</span>
  <span class="sh_keyword">if</span> <span class="sh_symbol">(</span>err<span class="sh_symbol">)</span> <span class="sh_cbracket">{</span>
    console<span class="sh_symbol">.</span><span class="sh_function">error</span><span class="sh_symbol">(</span><span class="sh_string">'Произошла ошибка при чтении файла!'</span><span class="sh_symbol">,</span> err<span class="sh_symbol">);</span>
    <span class="sh_keyword">return</span><span class="sh_symbol">;</span>
  <span class="sh_cbracket">}</span>
  <span class="sh_comment">// Иначе обрабаиываем данные</span>
<span class="sh_cbracket">}</span><span class="sh_symbol">);</span>
</code></pre>
</li>
<li><p>Когда вызван асинхронный метод на объекте, который является <code>EventEmitter</code>-ом,
ошибки могут быть преобразованы в событие <code>'error'</code> этого объекта.</p>
<pre class="sh_sourceCode"><code class="lang-js"><span class="sh_keyword">const</span> net <span class="sh_symbol">=</span> <span class="sh_function">require</span><span class="sh_symbol">(</span><span class="sh_string">'net'</span><span class="sh_symbol">);</span>
<span class="sh_keyword">const</span> connection <span class="sh_symbol">=</span> net<span class="sh_symbol">.</span><span class="sh_function">connect</span><span class="sh_symbol">(</span><span class="sh_string">'localhost'</span><span class="sh_symbol">);</span>

<span class="sh_comment">// Добавление обработчика события 'error' для потока:</span>
connection<span class="sh_symbol">.</span><span class="sh_function">on</span><span class="sh_symbol">(</span><span class="sh_string">'error'</span><span class="sh_symbol">,</span> <span class="sh_symbol">(</span>err<span class="sh_symbol">)</span> <span class="sh_symbol">=&gt;</span> <span class="sh_cbracket">{</span>
  <span class="sh_comment">// Если соединение прервано сервером, или если вообще</span>
  <span class="sh_comment">// не возможно соединиться, или при ошибке любого сорта, обнаруженной</span>
  <span class="sh_comment">// соединением, ошибка будет передана сюда.</span>
  console<span class="sh_symbol">.</span><span class="sh_function">error</span><span class="sh_symbol">(</span>err<span class="sh_symbol">);</span>
<span class="sh_cbracket">}</span><span class="sh_symbol">);</span>

connection<span class="sh_symbol">.</span><span class="sh_function">pipe</span><span class="sh_symbol">(</span>process<span class="sh_symbol">.</span>stdout<span class="sh_symbol">);</span>
</code></pre>
</li>
<li><p>Горсточка обычно асинхронных медодов в Node.js API по прежнему может использовать
сеханизм <code>throw</code> для возбуждения исключения, которое должно обрабатываться с использованием
<code>try / catch</code>. Нет полного списка этих методов; пожалоуйста
смотрите документацию к каждому методу для определения, какой механизм обработки ошибок требуется.</p>
</li>
</ul>
<p>Использхование механизма события <code>'error'</code> является наиболее общим для <a href="https://nodejs.org/dist/latest-v6.x/docs/api/stream.html">stream-based</a>
и <a href="https://nodejs.org/dist/latest-v6.x/docs/api/events.html#events_class_eventemitter">event emitter-based</a> API, которые сами по себе представляют серию
асинхронных операций во времени (в отличии от одной операции, которая может пройти удачно или нет).</p>
<p>Для <em>всех</em> объектов <code>EventEmitter</code>, если обработчик события <code>'error'</code> не
предоставлен, ошибка будет выброшена с использованием процесса Node.js для сообщения о
необработанном исключении и крах, за одним исключением: модуль <a href="https://nodejs.org/dist/latest-v6.x/docs/api/domain.html"><code>domain</code></a> используется как
описано, или имеется зарегистрированный обработчик для события
<a href="https://nodejs.org/dist/latest-v6.x/docs/api/process.html#process_event_uncaughtexception"><code>process.on('uncaughtException')</code></a>.</p>
<pre class="sh_sourceCode"><code class="lang-js"><span class="sh_keyword">const</span> EventEmitter <span class="sh_symbol">=</span> <span class="sh_function">require</span><span class="sh_symbol">(</span><span class="sh_string">'events'</span><span class="sh_symbol">);</span>
<span class="sh_keyword">const</span> ee <span class="sh_symbol">=</span> <span class="sh_keyword">new</span> <span class="sh_function">EventEmitter</span><span class="sh_symbol">();</span>

<span class="sh_function">setImmediate</span><span class="sh_symbol">(()</span> <span class="sh_symbol">=&gt;</span> <span class="sh_cbracket">{</span>
  <span class="sh_comment">// Это вызовет крах процесса, потому что обработчик события 'error'</span>
  <span class="sh_comment">// не добавлен.</span>
  ee<span class="sh_symbol">.</span><span class="sh_function">emit</span><span class="sh_symbol">(</span><span class="sh_string">'error'</span><span class="sh_symbol">,</span> <span class="sh_keyword">new</span> <span class="sh_predef_func">Error</span><span class="sh_symbol">(</span><span class="sh_string">'Это вызовет крах'</span><span class="sh_symbol">));</span>
<span class="sh_cbracket">}</span><span class="sh_symbol">);</span>
</code></pre>
<p>Ошибки, генерируемые этим способом <em>не могут</em> быть перехвачены с использованием <code>try / catch</code>, так как
они брошены <em>после</em> того как вызывающий код уже завершился.</p>
<p>Разработчики обязаны смотреть документцию для каждого метода для точного определения,
как этот метод генерирует ошибки, и как они распространяются.</p>
<h3>callback-и в стиле Node.js<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_node_js_style_callbacks" id="errors_node_js_style_callbacks">#</a></span></h3>
<!--type=misc-->
<p>Большинство асинхронных методов, обрабатываемых(exposed) ядром API Node.js, следуют характерному для данного языка
шаблону, называемому "callback в стиле Node.js"("Node.js style callback"). В этом шаблоне, 
callback-функция передается в метод как аргумент. Когда
операция завершится или произойдет ошибка, callback-функция вызовется с объектом
Error (если есть), переданным как первый аргумент. Если не произошло ошибки,
в качестве первого аргумента будет передан <code>null</code>.</p>
<pre class="sh_sourceCode"><code class="lang-js"><span class="sh_keyword">const</span> fs <span class="sh_symbol">=</span> <span class="sh_function">require</span><span class="sh_symbol">(</span><span class="sh_string">'fs'</span><span class="sh_symbol">);</span>

<span class="sh_keyword">function</span> <span class="sh_function">nodeStyleCallback</span><span class="sh_symbol">(</span>err<span class="sh_symbol">,</span> data<span class="sh_symbol">)</span> <span class="sh_cbracket">{</span>
 <span class="sh_keyword">if</span> <span class="sh_symbol">(</span>err<span class="sh_symbol">)</span> <span class="sh_cbracket">{</span>
   console<span class="sh_symbol">.</span><span class="sh_function">error</span><span class="sh_symbol">(</span><span class="sh_string">'Произошла ошибка'</span><span class="sh_symbol">,</span> err<span class="sh_symbol">);</span>
   <span class="sh_keyword">return</span><span class="sh_symbol">;</span>
 <span class="sh_cbracket">}</span>
 console<span class="sh_symbol">.</span><span class="sh_function">log</span><span class="sh_symbol">(</span>data<span class="sh_symbol">);</span>
<span class="sh_cbracket">}</span>

fs<span class="sh_symbol">.</span><span class="sh_function">readFile</span><span class="sh_symbol">(</span><span class="sh_string">'/некоторый/файл/который/не-существует'</span><span class="sh_symbol">,</span> nodeStyleCallback<span class="sh_symbol">);</span>
fs<span class="sh_symbol">.</span><span class="sh_function">readFile</span><span class="sh_symbol">(</span><span class="sh_string">'/некоторый/файл/который/существует'</span><span class="sh_symbol">,</span> nodeStyleCallback<span class="sh_symbol">)</span>
</code></pre>
<p>The JavaScript <code>try / catch</code> mechanism <strong>cannot</strong> be used to intercept errors
generated by asynchronous APIs.  A common mistake for beginners is to try to
use <code>throw</code> inside a Node.js style callback:</p>
<pre class="sh_sourceCode"><code class="lang-js"><span class="sh_comment">// THIS WILL NOT WORK:</span>
<span class="sh_keyword">const</span> fs <span class="sh_symbol">=</span> <span class="sh_function">require</span><span class="sh_symbol">(</span><span class="sh_string">'fs'</span><span class="sh_symbol">);</span>

<span class="sh_keyword">try</span> <span class="sh_cbracket">{</span>
  fs<span class="sh_symbol">.</span><span class="sh_function">readFile</span><span class="sh_symbol">(</span><span class="sh_string">'/some/file/that/does-not-exist'</span><span class="sh_symbol">,</span> <span class="sh_symbol">(</span>err<span class="sh_symbol">,</span> data<span class="sh_symbol">)</span> <span class="sh_symbol">=&gt;</span> <span class="sh_cbracket">{</span>
    <span class="sh_comment">// mistaken assumption: throwing here...</span>
    <span class="sh_keyword">if</span> <span class="sh_symbol">(</span>err<span class="sh_symbol">)</span> <span class="sh_cbracket">{</span>
      <span class="sh_keyword">throw</span> err<span class="sh_symbol">;</span>
    <span class="sh_cbracket">}</span>
  <span class="sh_cbracket">}</span><span class="sh_symbol">);</span>
<span class="sh_cbracket">}</span> <span class="sh_keyword">catch</span><span class="sh_symbol">(</span>err<span class="sh_symbol">)</span> <span class="sh_cbracket">{</span>
  <span class="sh_comment">// This will not catch the throw!</span>
  console<span class="sh_symbol">.</span><span class="sh_function">log</span><span class="sh_symbol">(</span>err<span class="sh_symbol">);</span>
<span class="sh_cbracket">}</span>
</code></pre>
<p>This will not work because the callback function passed to <code>fs.readFile()</code> is
called asynchronously. By the time the callback has been called, the
surrounding code (including the <code>try { } catch(err) { }</code> block will have
already exited. Throwing an error inside the callback <strong>can crash the Node.js
process</strong> in most cases. If <a href="https://nodejs.org/dist/latest-v6.x/docs/api/domain.html">domains</a> are enabled, or a handler has been
registered with <code>process.on('uncaughtException')</code>, such errors can be
intercepted.</p>
<h2>Class: Error<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_class_error" id="errors_class_error">#</a></span></h2>
<!--type=class-->
<p>A generic JavaScript <code>Error</code> object that does not denote any specific
circumstance of why the error occurred. <code>Error</code> objects capture a "stack trace"
detailing the point in the code at which the <code>Error</code> was instantiated, and may
provide a text description of the error.</p>
<p>All errors generated by Node.js, including all System and JavaScript errors,
will either be instances of, or inherit from, the <code>Error</code> class.</p>
<h3>new Error(message)<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_new_error_message" id="errors_new_error_message">#</a></span></h3>
<p>Creates a new <code>Error</code> object and sets the <code>error.message</code> property to the
provided text message. If an object is passed as <code>message</code>, the text message
is generated by calling <code>message.toString()</code>. The <code>error.stack</code> property will
represent the point in the code at which <code>new Error()</code> was called. Stack traces
are dependent on <a href="https://github.com/v8/v8/wiki/Stack-Trace-API">V8's stack trace API</a>. Stack traces extend only to either
(a) the beginning of  <em>synchronous code execution</em>, or (b) the number of frames
given by the property <code>Error.stackTraceLimit</code>, whichever is smaller.</p>
<h3>Error.captureStackTrace(targetObject[, constructorOpt])<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_capturestacktrace_targetobject_constructoropt" id="errors_error_capturestacktrace_targetobject_constructoropt">#</a></span></h3>
<p>Creates a <code>.stack</code> property on <code>targetObject</code>, which when accessed returns
a string representing the location in the code at which
<code>Error.captureStackTrace()</code> was called.</p>
<pre class="sh_sourceCode"><code class="lang-js"><span class="sh_keyword">const</span> myObject <span class="sh_symbol">=</span> <span class="sh_cbracket">{}</span><span class="sh_symbol">;</span>
<span class="sh_predef_func">Error</span><span class="sh_symbol">.</span><span class="sh_function">captureStackTrace</span><span class="sh_symbol">(</span>myObject<span class="sh_symbol">);</span>
myObject<span class="sh_symbol">.</span>stack  <span class="sh_comment">// similar to `new Error().stack`</span>
</code></pre>
<p>The first line of the trace, instead of being prefixed with <code>ErrorType:
message</code>, will be the result of calling <code>targetObject.toString()</code>.</p>
<p>The optional <code>constructorOpt</code> argument accepts a function. If given, all frames
above <code>constructorOpt</code>, including <code>constructorOpt</code>, will be omitted from the
generated stack trace.</p>
<p>The <code>constructorOpt</code> argument is useful for hiding implementation
details of error generation from an end user. For instance:</p>
<pre class="sh_sourceCode"><code class="lang-js"><span class="sh_keyword">function</span> <span class="sh_function">MyError</span><span class="sh_symbol">()</span> <span class="sh_cbracket">{</span>
  <span class="sh_predef_func">Error</span><span class="sh_symbol">.</span><span class="sh_function">captureStackTrace</span><span class="sh_symbol">(</span><span class="sh_keyword">this</span><span class="sh_symbol">,</span> MyError<span class="sh_symbol">);</span>
<span class="sh_cbracket">}</span>

<span class="sh_comment">// Without passing MyError to captureStackTrace, the MyError</span>
<span class="sh_comment">// frame would show up in the .stack property. By passing</span>
<span class="sh_comment">// the constructor, we omit that frame and all frames above it.</span>
<span class="sh_keyword">new</span> <span class="sh_function">MyError</span><span class="sh_symbol">().</span>stack
</code></pre>
<h3>Error.stackTraceLimit<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_stacktracelimit" id="errors_error_stacktracelimit">#</a></span></h3>
<p>The <code>Error.stackTraceLimit</code> property specifies the number of stack frames
collected by a stack trace (whether generated by <code>new Error().stack</code> or
<code>Error.captureStackTrace(obj)</code>).</p>
<p>The default value is <code>10</code> but may be set to any valid JavaScript number. Changes
will affect any stack trace captured <em>after</em> the value has been changed.</p>
<p>If set to a non-number value, or set to a negative number, stack traces will
not capture any frames.</p>
<h4>error.message<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_message" id="errors_error_message">#</a></span></h4>
<p>Returns the string description of error as set by calling <code>new Error(message)</code>.
The <code>message</code> passed to the constructor will also appear in the first line of
the stack trace of the <code>Error</code>, however changing this property after the
<code>Error</code> object is created <em>may not</em> change the first line of the stack trace.</p>
<pre class="sh_sourceCode"><code class="lang-js"><span class="sh_keyword">const</span> err <span class="sh_symbol">=</span> <span class="sh_keyword">new</span> <span class="sh_predef_func">Error</span><span class="sh_symbol">(</span><span class="sh_string">'The message'</span><span class="sh_symbol">);</span>
console<span class="sh_symbol">.</span><span class="sh_function">log</span><span class="sh_symbol">(</span>err<span class="sh_symbol">.</span>message<span class="sh_symbol">);</span>
  <span class="sh_comment">// Prints: The message</span>
</code></pre>
<h4>error.stack<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_stack" id="errors_error_stack">#</a></span></h4>
<p>Returns a string describing the point in the code at which the <code>Error</code> was
instantiated.</p>
<p>For example:</p>
<pre class="sh_sourceCode"><code><span class="sh_predef_func">Error</span><span class="sh_symbol">:</span> Things keep happening<span class="sh_symbol">!</span>
   <span class="sh_normal">at </span><span class="sh_symbol">/</span><span class="sh_normal">home</span><span class="sh_symbol">/</span><span class="sh_normal">gbusey</span><span class="sh_symbol">/</span>file<span class="sh_symbol">.</span>js<span class="sh_symbol">:</span><span class="sh_number">525</span><span class="sh_symbol">:</span><span class="sh_number">2</span>
   at Frobnicator<span class="sh_symbol">.</span><span class="sh_function">refrobulate</span> <span class="sh_symbol">(</span><span class="sh_regexp">/home/g</span><span class="sh_normal">busey</span><span class="sh_symbol">/</span>business<span class="sh_symbol">-</span>logic<span class="sh_symbol">.</span>js<span class="sh_symbol">:</span><span class="sh_number">424</span><span class="sh_symbol">:</span><span class="sh_number">21</span><span class="sh_symbol">)</span>
   at Actor<span class="sh_symbol">.&lt;</span>anonymous<span class="sh_symbol">&gt;</span> <span class="sh_symbol">(</span><span class="sh_regexp">/home/g</span><span class="sh_normal">busey</span><span class="sh_symbol">/</span>actors<span class="sh_symbol">.</span>js<span class="sh_symbol">:</span><span class="sh_number">400</span><span class="sh_symbol">:</span><span class="sh_number">8</span><span class="sh_symbol">)</span>
   at <span class="sh_function">increaseSynergy</span> <span class="sh_symbol">(</span><span class="sh_regexp">/home/g</span><span class="sh_normal">busey</span><span class="sh_symbol">/</span>actors<span class="sh_symbol">.</span>js<span class="sh_symbol">:</span><span class="sh_number">701</span><span class="sh_symbol">:</span><span class="sh_number">6</span><span class="sh_symbol">)</span>
</code></pre><p>The first line is formatted as <code>&lt;error class name&gt;: &lt;error message&gt;</code>, and
is followed by a series of stack frames (each line beginning with "at ").
Each frame describes a call site within the code that lead to the error being
generated. V8 attempts to display a name for each function (by variable name,
function name, or object method name), but occasionally it will not be able to
find a suitable name. If V8 cannot determine a name for the function, only
location information will be displayed for that frame. Otherwise, the
determined function name will be displayed with location information appended
in parentheses.</p>
<p>It is important to note that frames are <strong>only</strong> generated for JavaScript
functions. If, for example, execution synchronously passes through a C++ addon
function called <code>cheetahify</code>, which itself calls a JavaScript function, the
frame representing the <code>cheetahify</code> call will <strong>not</strong> be present in the stack
traces:</p>
<pre class="sh_sourceCode"><code class="lang-js"><span class="sh_keyword">const</span> cheetahify <span class="sh_symbol">=</span> <span class="sh_function">require</span><span class="sh_symbol">(</span><span class="sh_string">'./native-binding.node'</span><span class="sh_symbol">);</span>

<span class="sh_keyword">function</span> <span class="sh_function">makeFaster</span><span class="sh_symbol">()</span> <span class="sh_cbracket">{</span>
  <span class="sh_comment">// cheetahify *synchronously* calls speedy.</span>
  <span class="sh_function">cheetahify</span><span class="sh_symbol">(</span><span class="sh_keyword">function</span> <span class="sh_function">speedy</span><span class="sh_symbol">()</span> <span class="sh_cbracket">{</span>
    <span class="sh_keyword">throw</span> <span class="sh_keyword">new</span> <span class="sh_predef_func">Error</span><span class="sh_symbol">(</span><span class="sh_string">'oh no!'</span><span class="sh_symbol">);</span>
  <span class="sh_cbracket">}</span><span class="sh_symbol">);</span>
<span class="sh_cbracket">}</span>

<span class="sh_function">makeFaster</span><span class="sh_symbol">();</span> <span class="sh_comment">// will throw:</span>
  <span class="sh_comment">// /home/gbusey/file.js:6</span>
  <span class="sh_comment">//     throw new Error('oh no!');</span>
  <span class="sh_comment">//           ^</span>
  <span class="sh_comment">// Error: oh no!</span>
  <span class="sh_comment">//     at speedy (/home/gbusey/file.js:6:11)</span>
  <span class="sh_comment">//     at makeFaster (/home/gbusey/file.js:5:3)</span>
  <span class="sh_comment">//     at Object.&lt;anonymous&gt; (/home/gbusey/file.js:10:1)</span>
  <span class="sh_comment">//     at Module._compile (module.js:456:26)</span>
  <span class="sh_comment">//     at Object.Module._extensions..js (module.js:474:10)</span>
  <span class="sh_comment">//     at Module.load (module.js:356:32)</span>
  <span class="sh_comment">//     at Function.Module._load (module.js:312:12)</span>
  <span class="sh_comment">//     at Function.Module.runMain (module.js:497:10)</span>
  <span class="sh_comment">//     at startup (node.js:119:16)</span>
  <span class="sh_comment">//     at node.js:906:3</span>
</code></pre>
<p>The location information will be one of:</p>
<ul>
<li><code>native</code>, if the frame represents a call internal to V8 (as in <code>[].forEach</code>).</li>
<li><code>plain-filename.js:line:column</code>, if the frame represents a call internal
 to Node.js.</li>
<li><code>/absolute/path/to/file.js:line:column</code>, if the frame represents a call in
a user program, or its dependencies.</li>
</ul>
<p>The string representing the stack trace is lazily generated when the
<code>error.stack</code> property is <strong>accessed</strong>.</p>
<p>The number of frames captured by the stack trace is bounded by the smaller of
<code>Error.stackTraceLimit</code> or the number of available frames on the current event
loop tick.</p>
<p>System-level errors are generated as augmented <code>Error</code> instances, which are
detailed <a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_system_errors">here</a>.</p>
<h2>Class: RangeError<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_class_rangeerror" id="errors_class_rangeerror">#</a></span></h2>
<p>A subclass of <code>Error</code> that indicates that a provided argument was not within the
set or range of acceptable values for a function; whether that is a numeric
range, or outside the set of options for a given function parameter.</p>
<p>For example:</p>
<pre class="sh_sourceCode"><code class="lang-js"><span class="sh_function">require</span><span class="sh_symbol">(</span><span class="sh_string">'net'</span><span class="sh_symbol">).</span><span class="sh_function">connect</span><span class="sh_symbol">(-</span><span class="sh_number">1</span><span class="sh_symbol">);</span>
  <span class="sh_comment">// throws RangeError, port should be &gt; 0 &amp;&amp; &lt; 65536</span>
</code></pre>
<p>Node.js will generate and throw <code>RangeError</code> instances <em>immediately</em> as a form
of argument validation.</p>
<h2>Class: ReferenceError<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_class_referenceerror" id="errors_class_referenceerror">#</a></span></h2>
<p>A subclass of <code>Error</code> that indicates that an attempt is being made to access a
variable that is not defined. Such errors commonly indicate typos in code, or
an otherwise broken program.</p>
<p>While client code may generate and propagate these errors, in practice, only V8
will do so.</p>
<pre class="sh_sourceCode"><code class="lang-js">doesNotExist<span class="sh_symbol">;</span>
  <span class="sh_comment">// throws ReferenceError, doesNotExist is not a variable in this program.</span>
</code></pre>
<p><code>ReferenceError</code> instances will have an <code>error.arguments</code> property whose value
is an array containing a single element: a string representing the variable
that was not defined.</p>
<pre class="sh_sourceCode"><code class="lang-js"><span class="sh_keyword">const</span> assert <span class="sh_symbol">=</span> <span class="sh_function">require</span><span class="sh_symbol">(</span><span class="sh_string">'assert'</span><span class="sh_symbol">);</span>
<span class="sh_keyword">try</span> <span class="sh_cbracket">{</span>
  doesNotExist<span class="sh_symbol">;</span>
<span class="sh_cbracket">}</span> <span class="sh_keyword">catch</span><span class="sh_symbol">(</span>err<span class="sh_symbol">)</span> <span class="sh_cbracket">{</span>
  <span class="sh_function">assert</span><span class="sh_symbol">(</span>err<span class="sh_symbol">.</span><span class="sh_predef_var">arguments</span><span class="sh_symbol">[</span><span class="sh_number">0</span><span class="sh_symbol">],</span> <span class="sh_string">'doesNotExist'</span><span class="sh_symbol">);</span>
<span class="sh_cbracket">}</span>
</code></pre>
<p>Unless an application is dynamically generating and running code,
<code>ReferenceError</code> instances should always be considered a bug in the code
or its dependencies.</p>
<h2>Class: SyntaxError<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_class_syntaxerror" id="errors_class_syntaxerror">#</a></span></h2>
<p>A subclass of <code>Error</code> that indicates that a program is not valid JavaScript.
These errors may only be generated and propagated as a result of code
evaluation. Code evaluation may happen as a result of <code>eval</code>, <code>Function</code>,
<code>require</code>, or <a href="https://nodejs.org/dist/latest-v6.x/docs/api/vm.html">vm</a>. These errors are almost always indicative of a broken
program.</p>
<pre class="sh_sourceCode"><code class="lang-js"><span class="sh_keyword">try</span> <span class="sh_cbracket">{</span>
  <span class="sh_function">require</span><span class="sh_symbol">(</span><span class="sh_string">'vm'</span><span class="sh_symbol">).</span><span class="sh_function">runInThisContext</span><span class="sh_symbol">(</span><span class="sh_string">'binary ! isNotOk'</span><span class="sh_symbol">);</span>
<span class="sh_cbracket">}</span> <span class="sh_keyword">catch</span><span class="sh_symbol">(</span>err<span class="sh_symbol">)</span> <span class="sh_cbracket">{</span>
  <span class="sh_comment">// err will be a SyntaxError</span>
<span class="sh_cbracket">}</span>
</code></pre>
<p><code>SyntaxError</code> instances are unrecoverable in the context that created them –
they may only be caught by other contexts.</p>
<h2>Class: TypeError<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_class_typeerror" id="errors_class_typeerror">#</a></span></h2>
<p>A subclass of <code>Error</code> that indicates that a provided argument is not an
allowable type. For example, passing a function to a parameter which expects a
string would be considered a TypeError.</p>
<pre class="sh_sourceCode"><code class="lang-js"><span class="sh_function">require</span><span class="sh_symbol">(</span><span class="sh_string">'url'</span><span class="sh_symbol">).</span><span class="sh_function">parse</span><span class="sh_symbol">(()</span> <span class="sh_symbol">=&gt;</span> <span class="sh_cbracket">{</span> <span class="sh_cbracket">}</span><span class="sh_symbol">);</span>
  <span class="sh_comment">// throws TypeError, since it expected a string</span>
</code></pre>
<p>Node.js will generate and throw <code>TypeError</code> instances <em>immediately</em> as a form
of argument validation.</p>
<h2>Exceptions vs. Errors<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_exceptions_vs_errors" id="errors_exceptions_vs_errors">#</a></span></h2>
<!--type=misc-->
<p>A JavaScript exception is a value that is thrown as a result of an invalid
operation or as the target of a <code>throw</code> statement. While it is not required
that these values are instances of <code>Error</code> or classes which inherit from
<code>Error</code>, all exceptions thrown by Node.js or the JavaScript runtime <em>will</em> be
instances of Error.</p>
<p>Some exceptions are <em>unrecoverable</em> at the JavaScript layer. Such exceptions
will <em>always</em> cause the Node.js process to crash. Examples include <code>assert()</code>
checks or <code>abort()</code> calls in the C++ layer.</p>
<h2>System Errors<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_system_errors" id="errors_system_errors">#</a></span></h2>
<p>System errors are generated when exceptions occur within the program's
runtime environment. Typically, these are operational errors that occur
when an application violates an operating system constraint such as attempting
to read a file that does not exist or when the user does not have sufficient
permissions.</p>
<p>System errors are typically generated at the syscall level: an exhaustive list
of error codes and their meanings is available by running <code>man 2 intro</code> or
<code>man 3 errno</code> on most Unices; or <a href="http://man7.org/linux/man-pages/man3/errno.3.html">online</a>.</p>
<p>In Node.js, system errors are represented as augmented <code>Error</code> objects with
added properties.</p>
<h3>Class: System Error<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_class_system_error" id="errors_class_system_error">#</a></span></h3>
<h4>error.code<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_code" id="errors_error_code">#</a></span></h4>
<h4>error.errno<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_errno" id="errors_error_errno">#</a></span></h4>
<p>Returns a string representing the error code, which is always <code>E</code> followed by
a sequence of capital letters, and may be referenced in <code>man 2 intro</code>.</p>
<p>The properties <code>error.code</code> and <code>error.errno</code> are aliases of one another and
return the same value.</p>
<h4>error.syscall<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_syscall" id="errors_error_syscall">#</a></span></h4>
<p>Returns a string describing the <a href="http://man7.org/linux/man-pages/man2/syscall.2.html">syscall</a> that failed.</p>
<h3>Common System Errors<span><a class="mark" href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_common_system_errors" id="errors_common_system_errors">#</a></span></h3>
<p>This list is <strong>not exhaustive</strong>, but enumerates many of the common system
errors encountered when writing a Node.js program. An exhaustive list may be
found <a href="http://man7.org/linux/man-pages/man3/errno.3.html">here</a>.</p>
<ul>
<li><p><code>EACCES</code> (Permission denied): An attempt was made to access a file in a way
forbidden by its file access permissions.</p>
</li>
<li><p><code>EADDRINUSE</code> (Address already in use):  An attempt to bind a server
(<a href="https://nodejs.org/dist/latest-v6.x/docs/api/net.html"><code>net</code></a>, <a href="https://nodejs.org/dist/latest-v6.x/docs/api/http.html"><code>http</code></a>, or <a href="https://nodejs.org/dist/latest-v6.x/docs/api/https.html"><code>https</code></a>) to a local address failed due to
another server on the local system already occupying that address.</p>
</li>
<li><p><code>ECONNREFUSED</code> (Connection refused): No connection could be made because the
target machine actively refused it. This usually results from trying to
connect to a service that is inactive on the foreign host.</p>
</li>
<li><p><code>ECONNRESET</code> (Connection reset by peer): A connection was forcibly closed by
a peer. This normally results from a loss of the connection on the remote
socket due to a timeout or reboot. Commonly encountered via the <a href="https://nodejs.org/dist/latest-v6.x/docs/api/http.html"><code>http</code></a>
and <a href="https://nodejs.org/dist/latest-v6.x/docs/api/net.html"><code>net</code></a> modules.</p>
</li>
<li><p><code>EEXIST</code> (File exists): An existing file was the target of an operation that
required that the target not exist.</p>
</li>
<li><p><code>EISDIR</code> (Is a directory): An operation expected a file, but the given
pathname was a directory.</p>
</li>
<li><p><code>EMFILE</code> (Too many open files in system): Maximum number of
<a href="https://en.wikipedia.org/wiki/File_descriptor">file descriptors</a> allowable on the system has been reached, and
requests for another descriptor cannot be fulfilled until at least one
has been closed. This is encountered when opening many files at once in
parallel, especially on systems (in particular, OS X) where there is a low
file descriptor limit for processes. To remedy a low limit, run
<code>ulimit -n 2048</code> in the same shell that will run the Node.js process.</p>
</li>
<li><p><code>ENOENT</code> (No such file or directory): Commonly raised by <a href="https://nodejs.org/dist/latest-v6.x/docs/api/fs.html"><code>fs</code></a> operations
to indicate that a component of the specified pathname does not exist -- no
entity (file or directory) could be found by the given path.</p>
</li>
<li><p><code>ENOTDIR</code> (Not a directory): A component of the given pathname existed, but
was not a directory as expected. Commonly raised by <a href="https://nodejs.org/dist/latest-v6.x/docs/api/fs.html#fs_fs_readdir_path_options_callback"><code>fs.readdir</code></a>.</p>
</li>
<li><p><code>ENOTEMPTY</code> (Directory not empty): A directory with entries was the target
of an operation that requires an empty directory -- usually <a href="https://nodejs.org/dist/latest-v6.x/docs/api/fs.html#fs_fs_unlink_path_callback"><code>fs.unlink</code></a>.</p>
</li>
<li><p><code>EPERM</code> (Operation not permitted): An attempt was made to perform an
operation that requires elevated privileges.</p>
</li>
<li><p><code>EPIPE</code> (Broken pipe): A write on a pipe, socket, or FIFO for which there is
no process to read the data. Commonly encountered at the <a href="https://nodejs.org/dist/latest-v6.x/docs/api/net.html"><code>net</code></a> and
<a href="https://nodejs.org/dist/latest-v6.x/docs/api/http.html"><code>http</code></a> layers, indicative that the remote side of the stream being
written to has been closed.</p>
</li>
<li><p><code>ETIMEDOUT</code> (Operation timed out): A connect or send request failed because
the connected party did not properly respond after a period of time. Usually
encountered by <a href="https://nodejs.org/dist/latest-v6.x/docs/api/http.html"><code>http</code></a> or <a href="https://nodejs.org/dist/latest-v6.x/docs/api/net.html"><code>net</code></a> -- often a sign that a <code>socket.end()</code>
was not properly called.</p>
</li>
</ul>

      </div>
    </div>
  </div>
  <script src="./Errors Node.js v6.3.1 Manual &amp; Documentation_files/sh_main.js"></script>
  <script src="./Errors Node.js v6.3.1 Manual &amp; Documentation_files/sh_javascript.min.js"></script>
  <script>highlight(undefined, undefined, 'pre');</script>



</body></html>
